services:
  # Single Unified Service (Nginx + FastAPI)
  - type: web
    name: interview_coach_prep
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DB_NAME
        value: interview_coach
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_SECONDS
        value: 2400
      - key: EMAILJS_PUBLIC_KEY
        sync: false
      - key: EMAILJS_SERVICE_ID
        sync: false
      - key: EMAILJS_TEMPLATE_ID
        sync: false
      - key: CAREERJET_API_KEY
        sync: false
